"""empty message

Revision ID: 7d120b9be100
Revises: 0a09b4cfebab
Create Date: 2022-09-02 13:35:28.959656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d120b9be100'
down_revision = '0a09b4cfebab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
